package be.ac.ulb.lisa.idot.dicom;

/**
 * DICOM Exception.
 * 
 * DICOM exception occurs when the parsing of the DICOM file
 * is not possible or if the DICOM file is not supported by
 * the software.
 * 
 * @author Pierre Malarme
 * @version 1.0
 *
 */
public class DICOMException extends Exception {
	
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -2837146355840633988L;

	public DICOMException() {
		super();
	}
	
	public DICOMException(String msg) {
		super(msg);
	}
	
	public DICOMException(String msg, Throwable throwable) {
		super(msg, throwable);
	}
	
	public DICOMException(Throwable throwable) {
		super(throwable);
	}

}
